name: Lint

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Lint the project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - run: make test